version: "3.9"
services:
  ctf:
    hostname: 'ctf-box'
    build:
      context: .
      args:
        USER: cf12
        PASS: cf12
        SSH_PORT: 4444

    ports:
      - "4444:4444"
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
    volumes:
      - ~/ctf:/data

    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE

    # network_mode: host

