version: "3.9"
services:
  ctf:
    hostname: 'ctf-box'
    build:
      context: .
      args:
        USER: cf12
        PASS: cf12
        SSH_PORT: 4444

    # ports:
    #   - "4444:22"
    #   - "5000:5000"
    volumes:
      - /data/ctf:/data

    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE

    network_mode: host

